BAAS/Models/heartrate_daily.cs
using System.ComponentModel.DataAnnotations;
namespace BAAS.Models
{
    public class heartrate_daily
    {
        [Key]
        public int hrd_id { get; set; } 
        public int? person { get; set; }
        public int? fitbit { get; set; }
        public int? resting_heartrate { get; set; }
        public DateTime? timestamp { get; set; }
        public string? creationdate { get; set; }
        //public person Person { get; set; }


    }
}

BAAS/Models/person.cs
using System.ComponentModel.DataAnnotations;
namespace BAAS.Models

{
    public class person
    {
        
        [Key]
        public int person_id { get; set; }
        public string? gender { get; set; }
        public int? age { get; set; }
        public int? height { get; set; }
        public int? weight { get; set; }
        public string? firstname { get; set; }
        public int person1 { get; set; }
        public int? fitbit { get; set; }
        public string? client_id { get; set; }
        public string? client_secret { get; set; }
        /*public List<activity_information>? activity_information { get; set; }  
        public List<exercise_information>? exercise_information { get; set; }  
        public List<heartrate_information>? heartrate_information { get; set; }    
        public List<heartrate_daily>? heartrate_daily { get; set; }
        public List<sleep_information>? sleep_information { get; set; }   */
        
    }
    [MetadataType(typeof(person))]
    public partial class CheckId
    {
        //[Compare("person_id")]
        public int? Check_Id { get; set; }
    }

}

BAAS/Controllers/personController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BAAS.Data;
using BAAS.Models;
using System.Dynamic;
using Newtonsoft.Json;




namespace BAAS.Controllers
{
    public class personController : Controller
    {
        private readonly ApplicationDbContext _context;

        public personController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: person
        public async Task<IActionResult> Index()
        {
            return View(await _context.person.ToListAsync());
        }
       
      

       
            //Get: person/activity
        public async Task<IActionResult> Activity(int? id)
        {
            return View(await _context.activity_information.Where(p=> p.person == id).ToListAsync());
        }


        //GET: person/exercise

        public async Task<IActionResult> Exercise(int? id)
        {
            return View(await _context.exercise_information.Where(p => p.person == id).ToListAsync());
        }

        //Get: person/heart rate
        public async Task<IActionResult> Heartrate(int? id)
        {
            return View(await _context.heartrate_information.Where(p => p.person == id).ToListAsync());
        }
        //Get: person/heartrate daily
        public async Task<IActionResult> Heartratedaily(int? id)
        {
            return View(await _context.heartrate_daily.Where(p => p.person == id).ToListAsync());
        }
        //Get: person/sleep
        public async Task<IActionResult> Sleep(int? id)
        {
            return View(await _context.sleep_information.Where(p => p.person == id).ToListAsync());
        }

    }
}

BAAS/Views/person/Activity.cshtml
@model IEnumerable<BAAS.Models.activity_information>

@{
    ViewData["Title"] = "Activity";
}

<h1>Activity details</h1>
<div>
    <button class="bg-secondary"> 
    <a asp-action="Index" class="text-dark">Back to person</a>
    </button>
</div>
<br />
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.1-beta.2/Chart.min.js"></script>
<canvas id="chart" width="800" height="400"></canvas>
<script>
var chartData = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: [28, 48, 40, 19, 86, 27, 90]
        }
    ]
};


    var ctx = document.getElementById("chart").getContext("2d");
    window.myNewChart = new Chart(ctx).Line(chartData, {
        showTooltip: true,
        tooltipTemplate: "<%= value %>"
    });
</script>
@*<div>
   <link rel="stylesheet" href="~/doughnut.css">

<figure>
  <div class="figure-content">
    <svg width="25%" height="25%" viewBox="0 0 42 42" class="donut" aria-labelledby="health-title health-desc" role="img">
      <title id="beers-title"></title>
      <desc id="beers-desc"></desc>
      <circle class="donut-hole" cx="21" cy="21" r="15.91549430918954" fill="#fff" role="presentation"></circle>
      <circle class="donut-ring" cx="21" cy="21" r="15.91549430918954" fill="transparent" stroke="#d2d3d4" stroke-width="3" role="presentation"></circle>

      <circle class="donut-segment" cx="21" cy="21" r="15.91549430918954" fill="transparent" stroke="#ce4b99" stroke-width="3" stroke-dasharray="40 60" stroke-dashoffset="25" aria-labelledby="donut-segment-1-title donut-segment-1-desc">
        <title id="donut-segment-1-title"></title>
        <desc id="donut-segment-1-desc"></desc>
      </circle>
      <circle class="donut-segment" cx="21" cy="21" r="15.91549430918954" fill="transparent" stroke="#b1c94e" stroke-width="3" stroke-dasharray="20 80" stroke-dashoffset="85">
        <title id="donut-segment-2-title"></title>
        <desc id="donut-segment-2-desc"></desc>
      </circle>
      <circle class="donut-segment" cx="21" cy="21" r="15.91549430918954" fill="transparent" stroke="#377bbc" stroke-width="3" stroke-dasharray="30 70" stroke-dashoffset="65">
        <title id="donut-segment-3-title"></title>
        <desc id="donut-segment-3-desc"></desc>
      </circle>
      <!-- unused 10% -->
      <g class="chart-text">
        <text x="25%" y="25%" class="chart-number">
          @foreach(var user in Model){@Html.DisplayFor(u=>user.creationdate);}
        </text>
        <text x="25%" y="25%" class="chart-label">
          Stress
        </text>
      </g>
    </svg>
  </div>
  <figcaption class="figure-key">
    <p class="sr-only"></p>

    <ul class="figure-key-list" aria-hidden="true" role="presentation">
      <li>
                    <span class="shape-circle shape-fuschia"></span> Heart rate &nbsp; @{
                        foreach(var user in Model){
                         @Html.DisplayFor(u=>user.minutes_fairly_active);}
                    }
      </li>
      <li>
        <span class="shape-circle shape-lemon-lime"></span> Steps &nbsp;@foreach(var user in Model){@Html.DisplayFor(u=>user.minutes_lightly_active);} ;
      </li>
      <li>
        <span class="shape-circle shape-blue"></span> Sleep &nbsp; @foreach(var user in Model){@Html.DisplayFor(u=>user.steps);}
      </li>
      </li>
    </ul>
  </figcaption>
</figure>
</div>*@

<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br />

<div class="row">
    <div class="col-8">
       
        
        <div id="Layer1" style="position:absolute; width:1050px; height:300px; z-index:1; overflow: scroll;"> 
        <table class="table" style="border-left: 5px solid black; height: 200px}">
           
            <thead>
                
                <tr>
                   <th scope="col">Activity_id</th>
                   <th scope="col">Creationdate</th>
                   <th scope="col">Steps</th> 
                   <th scope="col">Mins sedentary</th>
                   <th scope="col">Distance</th>
                   <th scope="col">Floors</th>
                   <th scope="col">Mins lightly active</th>
                   <th scope="col">Mins fairly active</th>
                   <th scope="col">Mins very active</th>
                   <th scope="col">Activity calories</th>
                   <th scope="col">Calories burned</th>
                   <th scope="col">Person</th> 
                   <th scope="col">Fitbit</th>   
                </tr>
            </thead>
               
            @foreach (var user in Model)
            {
             <tbody>
                
            <tr>
                <td>@Html.DisplayFor(u => user.activity_id) </td>
                <td>@Html.DisplayFor(u => user.creationdate) </td>
                <td>@Html.DisplayFor(u => user.steps) </td>
                <td>@Html.DisplayFor(u => user.minutes_sedentary) </td>
                <td>@Html.DisplayFor(u => user.distance) </td>
                <td>@Html.DisplayFor(u => user.floors) </td>
                <td>@Html.DisplayFor(u => user.minutes_lightly_active) </td>
                <td>@Html.DisplayFor(u => user.minutes_fairly_active) </td>
                <td>@Html.DisplayFor(u => user.minutes_very_active) </td>
                <td>@Html.DisplayFor(u => user.activity_calories) </td>
                <td>@Html.DisplayFor(u => user.calories_burned) </td>
                <td>@Html.DisplayFor(u => user.person) </td>
                <td>@Html.DisplayFor(u => user.fitbit) </td>   
            </tr>
            
            </tbody>
                                   
          }
          
            
        </table>
        </div>
    </div>
</div>

BAAS/Views/person/Exercise.cshtml
@model IEnumerable<BAAS.Models.exercise_information>

@{
    ViewData["Title"] = "Exercise";
}

<h1>Exercise details</h1>
<div>
    <button class="bg-info"> 
    <a asp-action="Index" class="text-dark">Back to person </a>

    </button>
</div>

<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br />

<div class="row">
    <div class="col-8">
        <table class="table" style="border-left: 5px solid black; height: 200px}">
            <thead>
                <tr>
                   <th scope="col">Exercise_id</th>
                   <th scope="col">Exe_start_time</th>
                   <th scope="col">Exercise_name</th> 
                   <th scope="col">Exe_active_duration</th>
                   <th scope="col">Exe_Avg_HR</th>
                   <th scope="col">Calories_burned</th>
                   <th scope="col">Distance</th>
                   <th scope="col">Exe_overall_duration</th>
                   <th scope="col">Exe_pace</th>
                   <th scope="col">Distance_unit</th>
                   <th scope="col">Person</th> 
                   <th scope="col">Fitbit</th>
                </tr>
            </thead>
                              
         @foreach (var user in Model)
         {
             
            <tbody>
               <tr>
                    <td>@Html.DisplayFor(u => user.exercise_id) </td>
                    <td>@Html.DisplayFor(u => user.exercise_start_time) </td>
                    <td>@Html.DisplayFor(u => user.exercise_name) </td>
                    <td>@Html.DisplayFor(u => user.exercise_active_duration) </td>
                    <td>@Html.DisplayFor(u => user.exercise_average_heartrate) </td>
                    <td>@Html.DisplayFor(u => user.calories_burned) </td>
                    <td>@Html.DisplayFor(u => user.distance) </td>
                    <td>@Html.DisplayFor(u => user.exercise_overall_duration) </td>
                    <td>@Html.DisplayFor(u => user.exercise_pace) </td>
                    <td>@Html.DisplayFor(u => user.distance_unit) </td>
                    <td>@Html.DisplayFor(u => user.person) </td>
				    <td>@Html.DisplayFor(u => user.fitbit) </td> 
               </tr>
            </tbody>
                            
          }

        </table>
    </div>
</div>

BAAS/Views/person/Heartrate.cshtml
@model IEnumerable<BAAS.Models.heartrate_information>

@{
    ViewData["Title"] = "Heart rate";
}

<h1>Heart rate details</h1>
<div>
    <button class="bg-info"> 
    <a asp-action="Index" class="text-dark">Back to person </a>

    </button>
</div>


<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br />

<div class="row">
    <div class="col-8">
        <table class="table" style="border-left: 5px solid black; height: 200px}">
            <thead>
                <tr>
                    <th scope="col">Hrd_id</th>
                    <th scope="col">Creationdate</th>
                    <th scope="col">Average_resting_heartrate</th>
                    <th scope="col">Person</th>
                    <th scope="col">Fitbit</th>
                </tr>
            </thead>
                              
         @foreach (var user in Model)
         {
             
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(u => user.hri_id) </td>
                    <td>@Html.DisplayFor(u => user.creationdate) </td>
                    <td>@Html.DisplayFor(u => user.average_resting_heartrate) </td>
                    <td>@Html.DisplayFor(u => user.person) </td>
                    <td>@Html.DisplayFor(u => user.fitbit) </td>
                </tr>
            </tbody>
                            
          }

        </table>
    </div>
</div>
<br />

<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.1-beta.2/Chart.min.js"></script>
<canvas id="chart" width="800" height="400"></canvas>
<script>
var chartData = {
    
    labels:["January", "February", "March", "April", "May", "June", "July"],
    datasets:[
    {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",            
            data:[28, 48, 40, 19, 86, 27, 90]
    }
    
    ]    
    
};


    var ctx = document.getElementById("chart").getContext("2d");
    window.myNewChart = new Chart(ctx).Line(chartData, {
        showTooltip: true
        tooltipTemplate: "<%= value %>"
    });
    
   
</script>

BAAS/Views/person/Heartratedaily.cshtml
@model IEnumerable<BAAS.Models.heartrate_daily>

@{
    ViewData["Title"] = "Heart rate daily";
}

<h1>Heart rate daily details</h1>
<div>
    <button class="bg-info"> 
    <a asp-action="Index" class="text-dark">Back to person </a>

    </button>
</div>

<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br />

<div class="row">
    <div class="col-8">
        <table class="table" style="border-left: 5px solid black; height: 200px}">
            <thead>
                <tr>
                    <th scope="col">Hrd_id</th>
                    <th scope="col">Resting_heartrate</th>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Creationdates</th>
                    <th scope="col">Person</th>
                    <th scope="col">Fitbit</th>
                </tr>
            </thead>
                              
         @foreach (var user in Model)
         {
             
            <tbody>
                <tr>
                   <td>@Html.DisplayFor(u => user.hrd_id) </td>
                   <td>@Html.DisplayFor(u => user.resting_heartrate) </td>
                   <td>@Html.DisplayFor(u => user.timestamp) </td>
                   <td>@Html.DisplayFor(u => user.creationdate) </td>
                   <td>@Html.DisplayFor(u => user.person) </td>
                   <td>@Html.DisplayFor(u => user.fitbit) </td>
                </tr>
            </tbody>
                             
          }

        </table>
    </div>
</div>

BAAS/Views/person/Index.cshtml
@model IEnumerable<BAAS.Models.person>
 
@{
    
    ViewData["Title"] = "Index";
}

<h1>Users</h1>


<br />
@*<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br />*@

@*<div class="row">
    <div class="col-8">
 </div>
</div>*@
        <table class="table">
            <thead>
                <tr>
                   <th scope="col">Person_id</th>
                   <th scope="col">Gender</th>
                   <th scope="col">Age</th>
                   <th scope="col">Height</th>
                   <th scope="col">Weight</th>
                   <th scope="col">Activity</th>
                   <th scope="col">Exercise</th>
                   <th scope="col">Heart rate</th>
                   <th scope="col">Heart rate daily</th>
                   <th scope="col">Sleep</th>
                </tr>
            </thead>
                              
         @foreach (var user in Model)
         {
             
            <tbody>
               <tr>
                  <td>@Html.DisplayFor(u => user.person_id) </td>
                  <td>@Html.DisplayFor(u => user.gender) </td>
                  <td>@Html.DisplayFor(u => user.age) </td>
                  <td>@Html.DisplayFor(u => user.height) </td>
                  <td>@Html.DisplayFor(u => user.weight) </td>  
                  <td>
                      <a asp-controller="person" asp-action="Activity" asp-route-id="@user.person_id">Activity</a>
                  </td>
                  <td>
                      <a asp-controller="person" asp-action="Exercise" asp-route-id="@user.person_id">Exercise</a>
                  </td>
                  <td>
                      <a asp-controller="person" asp-action="Heartrate" asp-route-id="@user.person_id">Heart rate</a>
                  </td>  
                  <td>
                      <a asp-controller="person" asp-action="Heartratedaily" asp-route-id="@user.person_id">Heart rate daily</a>
                  </td> 
                  <td >
                      <a asp-controller="person" asp-action="Sleep" asp-route-id="@user.person_id">Sleep</a>
                  </td>  
              </tr>
            </tbody>
                            
          }

        </table>
   

    

BAAS/Views/person/Sleep.cshtml
@model IEnumerable<BAAS.Models.sleep_information>

@{
    ViewData["Title"] = "Sleep";
}

<h1>Sleep details</h1>
<div>
    <button class="bg-info"> 
    <a asp-action="Index" class="text-dark">Back to person </a>

    </button>
</div>

<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br />
<div class="row">
    <div class="col-8">
        <table class="table" style="border-left: 5px solid black; height: 200px}">
            <thead>
                <tr>
                    <th scope="col">Sleep_id</th>
                    <th scope="col">Creation_date</th>
                    <th scope="col">Min_asleep</th>
                    <th scope="col">Start_time</th>
                    <th scope="col">End_time</th>
                    <th scope="col">Min_awake</th>
                    <th scope="col">Num_of_awakenings</th>
                    <th scope="col">Min_in_bed</th>
                    <th scope="col">Person</th>
                    <th scope="col">Fitbit</th>
                </tr>
            </thead>
                              
         @foreach (var user in Model)
         {
             
            <tbody>
            <tr>
                <td>@Html.DisplayFor(u => user.sleep_id) </td>
                <td>@Html.DisplayFor(u => user.creationdate) </td>
                <td>@Html.DisplayFor(u => user.minutes_asleep) </td>
                <td>@Html.DisplayFor(u => user.start_time) </td>
                <td>@Html.DisplayFor(u => user.end_time) </td>
                <td>@Html.DisplayFor(u => user.minutes_awake) </td>
                <td>@Html.DisplayFor(u => user.number_of_awakenings) </td>
                <td>@Html.DisplayFor(u => user.minutes_in_bed) </td>
                <td>@Html.DisplayFor(u => user.person) </td>
				<td>@Html.DisplayFor(u => user.fitbit) </td>
                                  
            </tr>
            </tbody>
                            
          }

        </table>
    </div>
</div>
 
    